### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by mihaimocanu** [lucianmldvn/generator-pinkman#2]
![image](https://user-images.githubusercontent.com/1487950/48481921-d594f100-e817-11e8-905a-44fd2c749863.png)

To reproduce it:
npm install -g grunt-cli yo bower
npm install -g generator-pinkman
mkdir faclba
cd faclba
yo pinkman

Fix: create the .gitignore missing file

**Comment by lucianmldvn** [comment]
I couldn't reproduce this on my machine, the generator created the file.
