### ISSUE TITLE
grunt operations are not working

### ISSUE THREAD

**Issue by mihaimocanu** [lucianmldvn/generator-pinkman#3]
the new version of node is not compatible with the npm modules that are installed

**Comment by lucianmldvn** [comment]
For new projects, just update the generator running `npm install -g generator-pinkman` then follow the intructions in [README.MD](https://github.com/lucianmldvn/generator-pinkman/blob/master/README.md)

For existing projects run `npm install mocha@5.2.0 grunt-mocha@1.1.0` then you should be able to execute `grunt` and access your app at http://localhost:9001.
